CREATE DATABASE IF NOT EXISTS lumen_db;
USE lumen_db;

CREATE TABLE IF NOT EXISTS Users (
  Id INT AUTO_INCREMENT PRIMARY KEY,
  Email VARCHAR(255) NOT NULL,
  Name VARCHAR(255) NOT NULL,
  PasswordHash VARCHAR(255) NOT NULL
);
